#!/bin/bash
# define autoping application home here
# you can found 
#  [bin]
#  [jars]
#  [conf]
# folder in this path
AUTOPING=/danoo/content/zzh/autoping
#
# define JAVA Runtime jar
#
JAVA_RT=/danoo/content/jdk/lib/rt.jar

# export java classpath
export CLASSPATH=.:$JAVA_RT
export CLASSPATH=$CLASSPATH:$AUTOPING/conf
export CLASSPATH=$CLASSPATH:$AUTOPING/jars/autoping.jar
export CLASSPATH=$CLASSPATH:$AUTOPING/jars/nutz.jar
export CLASSPATH=$CLASSPATH:$AUTOPING/jars/log4j.jar

export JAVA_OPTS="-Xms256m -Xmx512m -Djava.awt.headless=true"

# run application
nohup java $JAVA_OPTS zzh.AutoPing 
#java $JAVA_OPTS zzh.AutoPing
